.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT\-IO" "7" "May 2011" "DevStructure" "Blueprint I/O"
.
.SH "NAME"
\fBblueprint\-io\fR \- centralized blueprint service
.
.SH "SYNOPSIS"
TODO
.
.SH "DESCRIPTION"
TODO
.
.SH "OPTIONS"
TODO
.
.SH "FILES"
TODO
.
.SH "THEME SONG"
Girl Talk \- "Let It Out"
.
.SH "AUTHOR"
Richard Crowley \fIrichard@devstructure\.com\fR
.
.SH "SEE ALSO"
\fBblueprint\-io\-server\fR(7) accepts \fBblueprint\-push\fR(1) and \fBblueprint\-pull\fR(1) requests, which \fBblueprint\-io\fR adds to the \fBblueprint\fR(1) suite\.
