.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLUEPRINT\-IO" "7" "June 2011" "DevStructure" "Blueprint I/O"
.
.SH "NAME"
\fBblueprint\-io\fR \- push and pull blueprints
.
.SH "SYNOPSIS"
.
.nf

blueprint push foo
blueprint pull https://devstructure\.com/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_\-/foo
.
.fi
.
.SH "DESCRIPTION"
Blueprint I/O pushes and pulls blueprints to and from a remote Blueprint I/O Server, making it easy to share and reuse blueprints on different machines\. DevStructure provides a free Blueprint I/O Server at \fIhttps://devstructure\.com\fR, which stores blueprints in Amazon S3\. Alternatively, you can supply your own backend server\.
.
.SH "FILES"
.
.TP
\fB~/\.blueprints\.git\fR
The local repsitory where blueprints are stored, each on its own branch\.
.
.TP
\fB/etc/blueprint\-io\.cfg\fR, \fB~/\.blueprint\-io\.cfg\fR
Optional INI\-style configuration files for specifying a \fBserver\fR and \fBsecret\fR value\.
.
.SH "EXAMPLES"
Example \fB~/\.blueprint\-io\.cfg\fR:
.
.IP "" 4
.
.nf

[default]
server = https://devstructure\.com
secret = 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_\-
.
.fi
.
.IP "" 0
.
.P
The \fIserver\fR in this case specifies the default and may be omitted\.
.
.SH "THEME SONG"
Girl Talk \- "Let It Out"
.
.SH "AUTHOR"
.
.IP "\(bu" 4
Matt Tanase \fImatt@devstructure\.com\fR
.
.IP "\(bu" 4
Richard Crowley \fIrichard@devstructure\.com\fR
.
.IP "" 0
.
.SH "SEE ALSO"
\fBblueprint\-push\fR(1) and \fBblueprint\-pull\fR(1), which \fBblueprint\-io\fR adds to the \fBblueprint\fR(1) suite\.
